name: Portal CI

on: [push, pull_request]

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  check:
    name: Ubuntu 21.04 build
    runs-on: ubuntu-latest
    container: ubuntu:21.04
    strategy:
      matrix:
        compiler: ['gcc', 'clang']

    env:
      CC: ${{ matrix.compiler }}
      CFLAGS: -fsanitize=undefined -fsanitize-undefined-trap-on-error -fsanitize=address -Wp,-D_FORTIFY_SOURCE=2

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get upgrade -y
        apt-get install -y make automake autoconf libtool gettext autopoint ${{ matrix.compiler }} \
          gtk-doc-tools shared-mime-info desktop-file-utils gnome-desktop-testing xmlto \
          libglib2.0-dev libgeoclue-2-dev libjson-glib-dev libfontconfig1-dev libfuse-dev libportal-dev libpipewire-0.3-dev

    - name: Check out xdg-desktop-portal
      uses: actions/checkout@v2

    - name: Configure xdg-desktop-portal
      run: ./autogen.sh --disable-dependency-tracking

    - name: Build xdg-desktop-portal
      run: make -j $(getconf _NPROCESSORS_ONLN)

    - name: Run xdg-desktop-portal tests
      # TODO: Build with -j (currently ends up with hangs in the tests)
      run: make check
      env:
        TEST_IN_CI: 1
        ASAN_OPTIONS: detect_leaks=0 # Right now we're not fully clean, but this gets us use-after-free etc

    - name: Install xdg-desktop-portal
      run: make install

    - name: Run xdg-desktop-portal installed-tests
      run: |
        mkdir installed-test-logs/
        gnome-desktop-testing-runner --report-directory installed-test-logs/ xdg-desktop-portal
      env:
        G_MESSAGES_DEBUG: all
        TEST_IN_CI: 1
        ASAN_OPTIONS: detect_leaks=0 # Right now we're not fully clean, but this gets us use-after-free etc

    - name: Upload test logs
      uses: actions/upload-artifact@v2
      if: failure() || cancelled()
      with:
        name: test logs
        path: |
          tests/*.log
          test-suite.log
          installed-test-logs/

  xenial:
    name: Ubuntu 16.04 build (old glib)
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get update -y
        apt-get install -y software-properties-common
        add-apt-repository ppa:alexlarsson/flatpak
        apt-get install -y automake autoconf libtool gettext autopoint gcc \
          gtk-doc-tools shared-mime-info desktop-file-utils \
          libglib2.0-dev libjson-glib-dev libfontconfig1-dev libfuse-dev

    - name: Check out xdg-desktop-portal
      uses: actions/checkout@v2

    - name: Configure xdg-desktop-portal
      # TODO: Enable gtk-doc builds
      # Meson to old to build libportal
      # Could not find a pipewire package
      # Geoclue is in 18.04 too old
      run: ./autogen.sh --disable-pipewire --disable-geoclue --disable-libportal

    - name: Build xdg-desktop-portal
      run: make -j $(getconf _NPROCESSORS_ONLN)
